// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTC48DNcmL5ISqEOKuLj6FksOpMQepkw',
    appId: '1:686171580682:web:e75be1faaf15ac901cf2f3',
    messagingSenderId: '686171580682',
    projectId: 'smart-yatra-282d4',
    authDomain: 'smart-yatra-282d4.firebaseapp.com',
    storageBucket: 'smart-yatra-282d4.firebasestorage.app',
    measurementId: 'G-WMLX3NG808',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePUyCbsiuFkqPtN3OuED2Yt5Y1MhDwRs',
    appId: '1:686171580682:android:4fe7438e4fe70f101cf2f3',
    messagingSenderId: '686171580682',
    projectId: 'smart-yatra-282d4',
    storageBucket: 'smart-yatra-282d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsg63q6eXFx7UR8x2v1GguyHHXsg3iacA',
    appId: '1:686171580682:ios:111c64278aaec7fe1cf2f3',
    messagingSenderId: '686171580682',
    projectId: 'smart-yatra-282d4',
    storageBucket: 'smart-yatra-282d4.firebasestorage.app',
    iosBundleId: 'com.example.smartYatraStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsg63q6eXFx7UR8x2v1GguyHHXsg3iacA',
    appId: '1:686171580682:ios:111c64278aaec7fe1cf2f3',
    messagingSenderId: '686171580682',
    projectId: 'smart-yatra-282d4',
    storageBucket: 'smart-yatra-282d4.firebasestorage.app',
    iosBundleId: 'com.example.smartYatraStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSTC48DNcmL5ISqEOKuLj6FksOpMQepkw',
    appId: '1:686171580682:web:93bee4704e79f09e1cf2f3',
    messagingSenderId: '686171580682',
    projectId: 'smart-yatra-282d4',
    authDomain: 'smart-yatra-282d4.firebaseapp.com',
    storageBucket: 'smart-yatra-282d4.firebasestorage.app',
    measurementId: 'G-MCSE9D8W89',
  );
}
